# Default values for data-service Helm chart
# This is a YAML-formatted file.

replicaCount: 3

image:
  repository: data-service
  pullPolicy: IfNotPresent
  tag: latest

nameOverride: ""
fullnameOverride: "data-service"

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "8000"
  prometheus.io/path: "/metrics"

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL

service:
  type: ClusterIP
  port: 80
  targetPort: 8000
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
    prometheus.io/path: "/metrics"

resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 2000m
    memory: 6Gi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Pods
          value: 2
          periodSeconds: 60

nodeSelector:
  kubernetes.io/role: application

tolerations: []

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: component
                operator: In
                values:
                  - data-service
          topologyKey: kubernetes.io/hostname
      - weight: 50
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: component
                operator: In
                values:
                  - data-service
          topologyKey: topology.kubernetes.io/zone

livenessProbe:
  httpGet:
    path: /health
    port: 8000
  initialDelaySeconds: 15
  periodSeconds: 20
  timeoutSeconds: 3
  successThreshold: 1
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /health
    port: 8000
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 2
  successThreshold: 1
  failureThreshold: 3

startupProbe:
  httpGet:
    path: /health
    port: 8000
  initialDelaySeconds: 10
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 12

env:
  APP_NAME: borrow-rate-engine
  LOG_LEVEL: INFO
  ENABLE_METRICS: "true"
  ENABLE_TRACING: "true"
  CACHE_SERVICE_URL: http://cache-service:8000
  DB_POOL_SIZE: "20"
  DB_MAX_OVERFLOW: "10"
  DB_POOL_TIMEOUT: "30"
  DB_POOL_RECYCLE: "1800"
  SECLEND_API_BASE_URL: https://api.seclend.com/v1
  MARKET_API_BASE_URL: https://api.marketdata.com/v1
  EVENT_API_BASE_URL: https://api.eventcalendar.com/v1
  ENABLE_CIRCUIT_BREAKER: "true"
  ENABLE_FALLBACK: "true"
  ENABLE_CACHE: "true"
  API_TIMEOUT: "5"
  API_RETRY_COUNT: "3"
  API_RETRY_BACKOFF: "0.5"
  CIRCUIT_BREAKER_FAILURE_THRESHOLD: "5"
  CIRCUIT_BREAKER_RECOVERY_TIMEOUT: "60"
  CIRCUIT_BREAKER_SUCCESS_THRESHOLD: "3"

configmap:
  enabled: true
  name: data-service-config
  data:
    APP_NAME: borrow-rate-engine
    LOG_LEVEL: INFO
    ENABLE_METRICS: "true"
    ENABLE_TRACING: "true"
    CACHE_SERVICE_URL: http://cache-service:8000
    DB_POOL_SIZE: "20"
    DB_MAX_OVERFLOW: "10"
    DB_POOL_TIMEOUT: "30"
    DB_POOL_RECYCLE: "1800"
    SECLEND_API_BASE_URL: https://api.seclend.com/v1
    MARKET_API_BASE_URL: https://api.marketdata.com/v1
    EVENT_API_BASE_URL: https://api.eventcalendar.com/v1
    ENABLE_CIRCUIT_BREAKER: "true"
    ENABLE_FALLBACK: "true"
    ENABLE_CACHE: "true"
    API_TIMEOUT: "5"
    API_RETRY_COUNT: "3"
    API_RETRY_BACKOFF: "0.5"
    CIRCUIT_BREAKER_FAILURE_THRESHOLD: "5"
    CIRCUIT_BREAKER_RECOVERY_TIMEOUT: "60"
    CIRCUIT_BREAKER_SUCCESS_THRESHOLD: "3"

secrets:
  enabled: true
  database:
    name: database-credentials
    keys:
      - url
      - host
      - port
      - name
      - user
      - password
  externalApi:
    name: external-api-credentials
    keys:
      - seclend_api_key
      - market_api_key
      - event_api_key
  redis:
    name: redis-credentials
    keys:
      - host
      - port
      - password

redis:
  enabled: true
  architecture: replication
  auth:
    enabled: true
    sentinel: true
    password: ""
  master:
    persistence:
      enabled: true
      size: 8Gi
  replica:
    replicaCount: 2
    persistence:
      enabled: true
      size: 8Gi
  sentinel:
    enabled: true
  metrics:
    enabled: true

common:
  enabled: true

podDisruptionBudget:
  enabled: true
  minAvailable: 2

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

terminationGracePeriodSeconds: 60