apiVersion: v2
name: audit-service
description: Helm chart for the Audit Service component of the Borrow Rate & Locate Fee Pricing Engine, responsible for recording all fee calculations for compliance and troubleshooting
version: 1.0.0
appVersion: 1.0.0
type: application
keywords:
  - audit
  - compliance
  - financial
  - logging
  - regulatory
home: https://github.com/organization/borrow-rate-locate-fee-engine
sources:
  - https://github.com/organization/borrow-rate-locate-fee-engine
maintainers:
  - name: DevOps Team
    email: devops@organization.com
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    version: ^1.0.0
    condition: common.enabled
    tags:
      - bitnami-common
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: ^12.0.0
    condition: postgresql.enabled
    tags:
      - audit-database
  - name: rabbitmq
    repository: https://charts.bitnami.com/bitnami
    version: ^11.0.0
    condition: rabbitmq.enabled
    tags:
      - audit-message-queue