apiVersion: v1
kind: Service
metadata:
  name: {{ include "audit-service.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "audit-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: audit
    part-of: borrow-rate-engine
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "audit-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}