apiVersion: v2
name: calculation-service
description: Helm chart for the Calculation Service component of the Borrow Rate & Locate Fee Pricing Engine. This service implements the core business logic for borrow rate and fee calculations, providing accurate and real-time pricing for securities lending transactions.
version: 0.1.0
appVersion: 1.0.0
type: application
keywords:
  - finance
  - borrow-rate
  - locate-fee
  - calculation
home: https://github.com/organization/borrow-rate-engine
sources:
  - https://github.com/organization/borrow-rate-engine
maintainers:
  - name: DevOps Team
    email: devops@organization.com
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    version: ^1.0.0
    condition: common.enabled
    tags:
      - bitnami-common
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: ^17.0.0
    condition: redis.enabled
    tags:
      - cache