---
# Database credentials secret
apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
  namespace: borrow-rate-engine
  labels:
    app: borrow-rate-engine
    component: database
    environment: ${ENV}
    managed-by: kustomize
type: Opaque
data:
  url: ${BASE64_DB_URL}
  username: ${BASE64_DB_USERNAME}
  password: ${BASE64_DB_PASSWORD}
  host: ${BASE64_DB_HOST}
  port: ${BASE64_DB_PORT}
  database: ${BASE64_DB_NAME}
---
# Redis credentials secret
apiVersion: v1
kind: Secret
metadata:
  name: redis-credentials
  namespace: borrow-rate-engine
  labels:
    app: borrow-rate-engine
    component: cache
    environment: ${ENV}
    managed-by: kustomize
type: Opaque
data:
  url: ${BASE64_REDIS_URL}
  host: ${BASE64_REDIS_HOST}
  port: ${BASE64_REDIS_PORT}
  password: ${BASE64_REDIS_PASSWORD}
  database: ${BASE64_REDIS_DB}
---
# External API credentials secret
apiVersion: v1
kind: Secret
metadata:
  name: external-api-credentials
  namespace: borrow-rate-engine
  labels:
    app: borrow-rate-engine
    component: external-api
    environment: ${ENV}
    managed-by: kustomize
type: Opaque
data:
  seclend_api_key: ${BASE64_SECLEND_API_KEY}
  market_api_key: ${BASE64_MARKET_API_KEY}
  event_api_key: ${BASE64_EVENT_API_KEY}
---
# JWT signing secret
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: borrow-rate-engine
  labels:
    app: borrow-rate-engine
    component: authentication
    environment: ${ENV}
    managed-by: kustomize
type: Opaque
data:
  secret_key: ${BASE64_JWT_SECRET_KEY}
---
# Encryption keys secret
apiVersion: v1
kind: Secret
metadata:
  name: encryption-keys
  namespace: borrow-rate-engine
  labels:
    app: borrow-rate-engine
    component: security
    environment: ${ENV}
    managed-by: kustomize
type: Opaque
data:
  field_encryption_key: ${BASE64_FIELD_ENCRYPTION_KEY}
  data_encryption_key: ${BASE64_DATA_ENCRYPTION_KEY}