# Loki Configuration for Borrow Rate & Locate Fee Pricing Engine
# Provides centralized log aggregation with 90-day retention
# Version: 2.8.0+

# Global authentication setting (disabled for internal use, should be enabled in production with proper auth)
auth_enabled: false

# Server configuration
server:
  http_listen_port: 3100
  grpc_listen_port: 9096
  http_server_read_timeout: 30s
  http_server_write_timeout: 30s
  grpc_server_max_recv_msg_size: 4194304  # 4MB
  grpc_server_max_send_msg_size: 4194304  # 4MB

# Ingester configuration - handles incoming log streams
ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 5m
  chunk_retain_period: 30s
  max_transfer_retries: 0
  wal:
    enabled: true
    dir: /tmp/loki/wal
    replay_memory_ceiling: 512MB

# Distributor configuration - receives logs and distributes to ingesters
distributor:
  ring:
    kvstore:
      store: inmemory

# Querier configuration - handles queries against stored logs
querier:
  engine:
    timeout: 3m
    max_look_back_period: 5m
  query_timeout: 1m
  max_concurrent: 20
  split_queries_by_interval: 15m

# Storage configuration - defines where and how logs are stored
storage_config:
  boltdb_shipper:
    active_index_directory: /tmp/loki/index
    cache_location: /tmp/loki/index_cache
    cache_ttl: 24h
    shared_store: filesystem
  filesystem:
    directory: /tmp/loki/chunks

# Limits configuration - controls resource usage
limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h  # 7 days
  ingestion_rate_mb: 10
  ingestion_burst_size_mb: 20
  per_stream_rate_limit: 5MB
  per_stream_rate_limit_burst: 10MB
  max_entries_limit_per_query: 10000
  max_query_series: 1000
  max_query_lookback: 2160h  # 90 days retention
  max_query_length: 721h     # ~30 days query window
  max_query_parallelism: 32
  cardinality_limit: 100000
  max_streams_per_user: 10000
  max_line_size: 256kb
  retention_period: 2160h    # 90 days retention

# Schema configuration - defines log index structure
schema_config:
  configs:
    - from: 2022-01-01
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

# Compactor configuration - handles compaction of stored data
compactor:
  working_directory: /tmp/loki/compactor
  shared_store: filesystem
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 150

# Ruler configuration - for alerting on log content
ruler:
  storage:
    type: local
    local:
      directory: /tmp/loki/rules
  rule_path: /tmp/loki/rules
  alertmanager_url: http://alertmanager:9093
  ring:
    kvstore:
      store: inmemory
  enable_api: true
  enable_alertmanager_v2: true
  evaluation_interval: 1m

# Analytics configuration
analytics:
  reporting_enabled: false

# Table manager for retention
table_manager:
  retention_deletes_enabled: true
  retention_period: 2160h  # 90 days retention

# Frontend configuration
frontend:
  compress_responses: true
  log_queries_longer_than: 10s
  max_outstanding_per_tenant: 2048
  tail_proxy_url: http://loki:3100

# Frontend worker configuration
frontend_worker:
  frontend_address: loki-frontend:9095
  grpc_client_config:
    max_send_msg_size: 104857600  # 100MB